package com.example.sachin.lecturereminder.dbModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CLASS_DATA".
 */
public class classData {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String topic;
    /** Not-null value. */
    private String professor;
    /** Not-null value. */
    private java.util.Date dateTime;
    /** Not-null value. */
    private String location;
    private long userDataId;

    public classData() {
    }

    public classData(Long id) {
        this.id = id;
    }

    public classData(Long id, String name, String topic, String professor, java.util.Date dateTime, String location, long userDataId) {
        this.id = id;
        this.name = name;
        this.topic = topic;
        this.professor = professor;
        this.dateTime = dateTime;
        this.location = location;
        this.userDataId = userDataId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getTopic() {
        return topic;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTopic(String topic) {
        this.topic = topic;
    }

    /** Not-null value. */
    public String getProfessor() {
        return professor;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setProfessor(String professor) {
        this.professor = professor;
    }

    /** Not-null value. */
    public java.util.Date getDateTime() {
        return dateTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDateTime(java.util.Date dateTime) {
        this.dateTime = dateTime;
    }

    /** Not-null value. */
    public String getLocation() {
        return location;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLocation(String location) {
        this.location = location;
    }

    public long getUserDataId() {
        return userDataId;
    }

    public void setUserDataId(long userDataId) {
        this.userDataId = userDataId;
    }

}
